/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package proyectocitas;

/**
 *
 * @author Edgar O
 */
public class Medico extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultarMedico
     */
    public Medico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelConsultarMedico = new javax.swing.JPanel();
        TipoID = new javax.swing.JComboBox<>();
        jLabelTipoID = new javax.swing.JLabel();
        jLabelPrimerNombre = new javax.swing.JLabel();
        jLabelIdPaciente = new javax.swing.JLabel();
        IdMedico = new javax.swing.JTextField();
        PrimerNombre = new javax.swing.JTextField();
        jLabelSegundoNombre = new javax.swing.JLabel();
        SegundoNombre = new javax.swing.JTextField();
        jLabelPrimerApellido = new javax.swing.JLabel();
        PrimerApellido = new javax.swing.JTextField();
        jLabelSegundoApellido = new javax.swing.JLabel();
        SegundoApellido = new javax.swing.JTextField();
        jLabelEspecialidad = new javax.swing.JLabel();
        Especialidad = new javax.swing.JComboBox<>();
        jLabelRegistroMedico = new javax.swing.JLabel();
        RegistroMedico = new javax.swing.JTextField();
        jLabelDepartamento = new javax.swing.JLabel();
        DepartamentoMedico = new javax.swing.JTextField();
        jLabelMunicipio = new javax.swing.JLabel();
        MunicipioMedico = new javax.swing.JTextField();
        jLabelDireccion = new javax.swing.JLabel();
        DireccionMedico = new javax.swing.JTextField();
        jLabelTelefono = new javax.swing.JLabel();
        TelefonoMedico = new javax.swing.JTextField();
        jLabelEstado = new javax.swing.JLabel();
        checkbox1 = new java.awt.Checkbox();
        checkbox2 = new java.awt.Checkbox();
        GuardarMedico = new javax.swing.JButton();
        ConsultarMedico = new javax.swing.JButton();
        EliminarMedico = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Médico");

        jPanelConsultarMedico.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Médico"));

        TipoID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Cedula de Ciudadania", "Cedula de Extrangería", "Pasaporte" }));
        TipoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoIDActionPerformed(evt);
            }
        });

        jLabelTipoID.setText("Tipo de Identificación:");

        jLabelPrimerNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPrimerNombre.setText("Primer Nombre: ");
        jLabelPrimerNombre.setToolTipText("");

        jLabelIdPaciente.setText("Numero de Identificación:");

        IdMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdMedicoActionPerformed(evt);
            }
        });

        PrimerNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrimerNombreActionPerformed(evt);
            }
        });

        jLabelSegundoNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelSegundoNombre.setText("Segundo Nombre: ");
        jLabelSegundoNombre.setToolTipText("");

        SegundoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SegundoNombreActionPerformed(evt);
            }
        });

        jLabelPrimerApellido.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPrimerApellido.setText("Primer Apellido: ");
        jLabelPrimerApellido.setToolTipText("");

        PrimerApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrimerApellidoActionPerformed(evt);
            }
        });

        jLabelSegundoApellido.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelSegundoApellido.setText("Segundo Apellido: ");
        jLabelSegundoApellido.setToolTipText("");

        SegundoApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SegundoApellidoActionPerformed(evt);
            }
        });

        jLabelEspecialidad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelEspecialidad.setText("Especialidad:");
        jLabelEspecialidad.setToolTipText("");

        Especialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Medicina General", "Ginecología", "Urología", "Medicina Interna", "Endocrinología", "Radiología", "Pediatría" }));
        Especialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspecialidadActionPerformed(evt);
            }
        });

        jLabelRegistroMedico.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelRegistroMedico.setText("Registro Médico:");
        jLabelRegistroMedico.setToolTipText("");

        RegistroMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroMedicoActionPerformed(evt);
            }
        });

        jLabelDepartamento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDepartamento.setText("Departamento:");
        jLabelDepartamento.setToolTipText("");

        DepartamentoMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepartamentoMedicoActionPerformed(evt);
            }
        });

        jLabelMunicipio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelMunicipio.setText("Municipio:");
        jLabelMunicipio.setToolTipText("");

        MunicipioMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MunicipioMedicoActionPerformed(evt);
            }
        });

        jLabelDireccion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDireccion.setText("Dirección de Residencia:");
        jLabelDireccion.setToolTipText("");

        DireccionMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DireccionMedicoActionPerformed(evt);
            }
        });

        jLabelTelefono.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTelefono.setText("Telefono de Contacto:");
        jLabelTelefono.setToolTipText("");

        TelefonoMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonoMedicoActionPerformed(evt);
            }
        });

        jLabelEstado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelEstado.setText("Estado:");
        jLabelEstado.setToolTipText("");

        checkbox1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        checkbox1.setLabel("Activo");

        checkbox2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        checkbox2.setLabel("Inactivo");

        GuardarMedico.setText("Guardar");
        GuardarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarMedicoActionPerformed(evt);
            }
        });

        ConsultarMedico.setText("Consultar");
        ConsultarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarMedicoActionPerformed(evt);
            }
        });

        EliminarMedico.setText("Eliminar");
        EliminarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarMedicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelConsultarMedicoLayout = new javax.swing.GroupLayout(jPanelConsultarMedico);
        jPanelConsultarMedico.setLayout(jPanelConsultarMedicoLayout);
        jPanelConsultarMedicoLayout.setHorizontalGroup(
            jPanelConsultarMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultarMedicoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelConsultarMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRegistroMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSegundoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIdPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelPrimerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTipoID)
                    .addComponent(jLabelDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTelefono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelConsultarMedicoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabelEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelConsultarMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelConsultarMedicoLayout.createSequentialGroup()
                        .addComponent(checkbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkbox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConsultarMedicoLayout.createSequentialGroup()
                        .addGroup(jPanelConsultarMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelConsultarMedicoLayout.createSequentialGroup()
                                .addComponent(GuardarMedico)
                                .addGap(27, 27, 27)
                                .addComponent(EliminarMedico)
                                .addGap(8, 8, 8))
                            .addComponent(IdMedico, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PrimerNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SegundoNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PrimerApellido, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SegundoApellido, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TipoID, javax.swing.GroupLayout.Alignment.LEADING, 0, 295, Short.MAX_VALUE)
                            .addComponent(Especialidad, javax.swing.GroupLayout.Alignment.LEADING, 0, 1, Short.MAX_VALUE)
                            .addComponent(RegistroMedico, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DepartamentoMedico, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MunicipioMedico, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DireccionMedico, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TelefonoMedico, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(78, 78, 78))))
            .addGroup(jPanelConsultarMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelConsultarMedicoLayout.createSequentialGroup()
                    .addGap(176, 176, 176)
                    .addComponent(ConsultarMedico)
                    .addContainerGap(282, Short.MAX_VALUE)))
        );
        jPanelConsultarMedicoLayout.setVerticalGroup(
            jPanelConsultarMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultarMedicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConsultarMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TipoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTipoID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelConsultarMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdPaciente)
                    .addComponent(IdMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelConsultarMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrimerNombre)
                    .addComponent(PrimerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelConsultarMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSegundoNombre)
                    .addComponent(SegundoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelConsultarMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrimerApellido)
                    .addComponent(PrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelConsultarMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSegundoApellido)
                    .addComponent(SegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelConsultarMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEspecialidad)
                    .addComponent(Especialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelConsultarMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRegistroMedico)
                    .addComponent(RegistroMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelConsultarMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDepartamento)
                    .addComponent(DepartamentoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelConsultarMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMunicipio)
                    .addComponent(MunicipioMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelConsultarMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDireccion)
                    .addComponent(DireccionMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelConsultarMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelefono)
                    .addComponent(TelefonoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanelConsultarMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkbox1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(checkbox2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanelConsultarMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GuardarMedico)
                    .addComponent(EliminarMedico))
                .addContainerGap())
            .addGroup(jPanelConsultarMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConsultarMedicoLayout.createSequentialGroup()
                    .addContainerGap(466, Short.MAX_VALUE)
                    .addComponent(ConsultarMedico)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelConsultarMedico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelConsultarMedico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("Médico\n");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConsultarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultarMedicoActionPerformed

    private void GuardarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuardarMedicoActionPerformed

    private void TelefonoMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonoMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonoMedicoActionPerformed

    private void DireccionMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DireccionMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DireccionMedicoActionPerformed

    private void MunicipioMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MunicipioMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MunicipioMedicoActionPerformed

    private void DepartamentoMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepartamentoMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DepartamentoMedicoActionPerformed

    private void RegistroMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistroMedicoActionPerformed

    private void EspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspecialidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EspecialidadActionPerformed

    private void SegundoApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SegundoApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SegundoApellidoActionPerformed

    private void PrimerApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrimerApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrimerApellidoActionPerformed

    private void SegundoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SegundoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SegundoNombreActionPerformed

    private void PrimerNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrimerNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrimerNombreActionPerformed

    private void IdMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdMedicoActionPerformed

    private void TipoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoIDActionPerformed

    private void EliminarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarMedicoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConsultarMedico;
    private javax.swing.JTextField DepartamentoMedico;
    private javax.swing.JTextField DireccionMedico;
    private javax.swing.JButton EliminarMedico;
    private javax.swing.JComboBox<String> Especialidad;
    private javax.swing.JButton GuardarMedico;
    private javax.swing.JTextField IdMedico;
    private javax.swing.JTextField MunicipioMedico;
    private javax.swing.JTextField PrimerApellido;
    private javax.swing.JTextField PrimerNombre;
    private javax.swing.JTextField RegistroMedico;
    private javax.swing.JTextField SegundoApellido;
    private javax.swing.JTextField SegundoNombre;
    private javax.swing.JTextField TelefonoMedico;
    private javax.swing.JComboBox<String> TipoID;
    private java.awt.Checkbox checkbox1;
    private java.awt.Checkbox checkbox2;
    private javax.swing.JLabel jLabelDepartamento;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelEspecialidad;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelIdPaciente;
    private javax.swing.JLabel jLabelMunicipio;
    private javax.swing.JLabel jLabelPrimerApellido;
    private javax.swing.JLabel jLabelPrimerNombre;
    private javax.swing.JLabel jLabelRegistroMedico;
    private javax.swing.JLabel jLabelSegundoApellido;
    private javax.swing.JLabel jLabelSegundoNombre;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelTipoID;
    private javax.swing.JPanel jPanelConsultarMedico;
    // End of variables declaration//GEN-END:variables
}
