/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package proyectocitas;

/**
 *
 * @author Edgar O
 */
public class Paciente extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultarPaciente
     */
    public Paciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fechaNacimient = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabelTipoID = new javax.swing.JLabel();
        jLabelIdPaciente = new javax.swing.JLabel();
        jLabelPrimerNombre = new javax.swing.JLabel();
        jLabelSegundoNombre = new javax.swing.JLabel();
        jLabelPrimerApellido = new javax.swing.JLabel();
        jLabelSegundoApellido = new javax.swing.JLabel();
        jLabelLugarNacimiento = new javax.swing.JLabel();
        jLabelFechaNacimiento = new javax.swing.JLabel();
        jLabelDepartamento = new javax.swing.JLabel();
        jLabelMunicipio = new javax.swing.JLabel();
        jLabelDireccionResidencia = new javax.swing.JLabel();
        jLabelRegimen = new javax.swing.JLabel();
        jLabelEPS = new javax.swing.JLabel();
        TipoID = new javax.swing.JComboBox<>();
        IdPaciente = new javax.swing.JTextField();
        PrimerNombre = new javax.swing.JTextField();
        SegundoNombre = new javax.swing.JTextField();
        PrimerApellido = new javax.swing.JTextField();
        SegundoApellido = new javax.swing.JTextField();
        LugarNacimiento = new javax.swing.JTextField();
        MunicipioNacimiento = new javax.swing.JTextField();
        DepartamentoNacimiento = new javax.swing.JTextField();
        DireccionPaciente = new javax.swing.JTextField();
        Regimen = new javax.swing.JComboBox<>();
        Eps = new javax.swing.JComboBox<>();
        ConsultarPaciente = new javax.swing.JButton();
        EliminarPaciente = new javax.swing.JButton();
        GuardarPaciente = new javax.swing.JButton();
        fechaNacimiento = new com.toedter.calendar.JDateChooser();

        fechaNacimient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaNacimientActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consultar Paciente");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Paciente"));

        jLabelTipoID.setText("Tipo de Identificación:");

        jLabelIdPaciente.setText("Numero de Identificación:");

        jLabelPrimerNombre.setText("Primer Nombre:");

        jLabelSegundoNombre.setText("Segundo Nombre:");

        jLabelPrimerApellido.setText("Primer Apellido:");

        jLabelSegundoApellido.setText("Segundo Apellido:");

        jLabelLugarNacimiento.setText("Lugar de Nacimiento:");

        jLabelFechaNacimiento.setText("Fecha de Nacimiento:");

        jLabelDepartamento.setText("Departamento:");

        jLabelMunicipio.setText("Municipio:");

        jLabelDireccionResidencia.setText("Dirección de Residencia:");

        jLabelRegimen.setText("Regimen:");

        jLabelEPS.setText("EPS:");

        TipoID.setEditable(true);
        TipoID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Cedula Ciudadania", "Tarjeta de Identidad", "Cedula de Extrangería", "Pasaporte", " " }));
        TipoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoIDActionPerformed(evt);
            }
        });

        IdPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdPacienteActionPerformed(evt);
            }
        });

        PrimerNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrimerNombreActionPerformed(evt);
            }
        });

        SegundoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SegundoNombreActionPerformed(evt);
            }
        });

        PrimerApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrimerApellidoActionPerformed(evt);
            }
        });

        SegundoApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SegundoApellidoActionPerformed(evt);
            }
        });

        LugarNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LugarNacimientoActionPerformed(evt);
            }
        });

        MunicipioNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MunicipioNacimientoActionPerformed(evt);
            }
        });

        DepartamentoNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepartamentoNacimientoActionPerformed(evt);
            }
        });

        DireccionPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DireccionPacienteActionPerformed(evt);
            }
        });

        Regimen.setEditable(true);
        Regimen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Subsidiado", "Contributivo ", " " }));
        Regimen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegimenActionPerformed(evt);
            }
        });

        Eps.setEditable(true);
        Eps.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Nueva EPS", "EPS Sura", "Sisben ", "Coosalud ", " " }));
        Eps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EpsActionPerformed(evt);
            }
        });

        ConsultarPaciente.setText("Consultar");
        ConsultarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarPacienteActionPerformed(evt);
            }
        });

        EliminarPaciente.setText("Eliminar");
        EliminarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarPacienteActionPerformed(evt);
            }
        });

        GuardarPaciente.setText("Guardar");
        GuardarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarPacienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelIdPaciente)
                            .addComponent(jLabelPrimerNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelSegundoNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelPrimerApellido, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelSegundoApellido, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelLugarNacimiento, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelFechaNacimiento, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelTipoID, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(IdPaciente)
                            .addComponent(PrimerNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(SegundoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(SegundoApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(PrimerApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(LugarNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(TipoID, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabelDepartamento)
                        .addGap(18, 18, 18)
                        .addComponent(DepartamentoNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelMunicipio, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelDireccionResidencia, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelRegimen, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelEPS, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(MunicipioNacimiento)
                                    .addComponent(DireccionPaciente)
                                    .addComponent(Regimen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Eps, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(ConsultarPaciente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(GuardarPaciente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(EliminarPaciente)))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipoID)
                    .addComponent(TipoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdPaciente)
                    .addComponent(IdPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrimerNombre)
                    .addComponent(PrimerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSegundoNombre)
                    .addComponent(SegundoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrimerApellido)
                    .addComponent(PrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSegundoApellido)
                    .addComponent(SegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLugarNacimiento)
                    .addComponent(LugarNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFechaNacimiento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DepartamentoNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDepartamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MunicipioNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMunicipio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDireccionResidencia)
                    .addComponent(DireccionPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRegimen)
                    .addComponent(Regimen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEPS)
                    .addComponent(Eps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConsultarPaciente)
                    .addComponent(EliminarPaciente)
                    .addComponent(GuardarPaciente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TipoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoIDActionPerformed

    private void IdPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdPacienteActionPerformed

    private void PrimerNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrimerNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrimerNombreActionPerformed

    private void SegundoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SegundoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SegundoNombreActionPerformed

    private void PrimerApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrimerApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrimerApellidoActionPerformed

    private void SegundoApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SegundoApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SegundoApellidoActionPerformed

    private void LugarNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LugarNacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LugarNacimientoActionPerformed

    private void MunicipioNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MunicipioNacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MunicipioNacimientoActionPerformed

    private void DepartamentoNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepartamentoNacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DepartamentoNacimientoActionPerformed

    private void DireccionPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DireccionPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DireccionPacienteActionPerformed

    private void RegimenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegimenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegimenActionPerformed

    private void EpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EpsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EpsActionPerformed

    private void ConsultarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultarPacienteActionPerformed

    private void EliminarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarPacienteActionPerformed

    private void GuardarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuardarPacienteActionPerformed

    private void fechaNacimientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaNacimientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaNacimientActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConsultarPaciente;
    private javax.swing.JTextField DepartamentoNacimiento;
    private javax.swing.JTextField DireccionPaciente;
    private javax.swing.JButton EliminarPaciente;
    private javax.swing.JComboBox<String> Eps;
    private javax.swing.JButton GuardarPaciente;
    private javax.swing.JTextField IdPaciente;
    private javax.swing.JTextField LugarNacimiento;
    private javax.swing.JTextField MunicipioNacimiento;
    private javax.swing.JTextField PrimerApellido;
    private javax.swing.JTextField PrimerNombre;
    private javax.swing.JComboBox<String> Regimen;
    private javax.swing.JTextField SegundoApellido;
    private javax.swing.JTextField SegundoNombre;
    private javax.swing.JComboBox<String> TipoID;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField fechaNacimient;
    private com.toedter.calendar.JDateChooser fechaNacimiento;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabelDepartamento;
    private javax.swing.JLabel jLabelDireccionResidencia;
    private javax.swing.JLabel jLabelEPS;
    private javax.swing.JLabel jLabelFechaNacimiento;
    private javax.swing.JLabel jLabelIdPaciente;
    private javax.swing.JLabel jLabelLugarNacimiento;
    private javax.swing.JLabel jLabelMunicipio;
    private javax.swing.JLabel jLabelPrimerApellido;
    private javax.swing.JLabel jLabelPrimerNombre;
    private javax.swing.JLabel jLabelRegimen;
    private javax.swing.JLabel jLabelSegundoApellido;
    private javax.swing.JLabel jLabelSegundoNombre;
    private javax.swing.JLabel jLabelTipoID;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
