/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectocitas;

/**
 *
 * @author Edgar O
 */
public class ProyectoCitas extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public ProyectoCitas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        opcRegistrarPaciente = new javax.swing.JMenuItem();
        opcRegistrarMedico = new javax.swing.JMenuItem();
        opcAsignarCita = new javax.swing.JMenuItem();
        opcConsultarPaciente = new javax.swing.JMenuItem();
        opcConsultarMédico = new javax.swing.JMenuItem();
        opcConsultarCita = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 308, Short.MAX_VALUE)
        );

        jMenu1.setText("Archivo ");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Menu");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        opcRegistrarPaciente.setText("Registrar Paciente");
        opcRegistrarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcRegistrarPacienteActionPerformed(evt);
            }
        });
        jMenu2.add(opcRegistrarPaciente);

        opcRegistrarMedico.setText("Registrar Médico");
        opcRegistrarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcRegistrarMedicoActionPerformed(evt);
            }
        });
        jMenu2.add(opcRegistrarMedico);

        opcAsignarCita.setText("Asignar Cita");
        opcAsignarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcAsignarCitaActionPerformed(evt);
            }
        });
        jMenu2.add(opcAsignarCita);

        opcConsultarPaciente.setText("Consultar Paciente");
        opcConsultarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcConsultarPacienteActionPerformed(evt);
            }
        });
        jMenu2.add(opcConsultarPaciente);

        opcConsultarMédico.setText("Consultar Médico");
        opcConsultarMédico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcConsultarMédicoActionPerformed(evt);
            }
        });
        jMenu2.add(opcConsultarMédico);

        opcConsultarCita.setText("Consultar Cita");
        opcConsultarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcConsultarCitaActionPerformed(evt);
            }
        });
        jMenu2.add(opcConsultarCita);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcRegistrarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcRegistrarPacienteActionPerformed
        // Vamos a llamar la otra ventana
        //Creamos un objeto
        RegistrarPaciente ventanaRegistrarPaciente = new RegistrarPaciente();
        escritorio.add(ventanaRegistrarPaciente);
        ventanaRegistrarPaciente.show(); 
    }//GEN-LAST:event_opcRegistrarPacienteActionPerformed

    private void opcRegistrarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcRegistrarMedicoActionPerformed
        // Vamos a llamar la otra ventana
        //Creamos un objeto
        RegistrarMedico ventanaRegistrarMedico = new RegistrarMedico();
        escritorio.add(ventanaRegistrarMedico);
        ventanaRegistrarMedico.show();
    }//GEN-LAST:event_opcRegistrarMedicoActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void opcAsignarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcAsignarCitaActionPerformed
        // TODO add your handling code here:
        // Vamos a llamar la otra ventana
        //Creamos un objeto
        AsignarCita ventanaAsignarCitaAction = new AsignarCita();
        escritorio.add(ventanaAsignarCitaAction);
        ventanaAsignarCitaAction.show();
    }//GEN-LAST:event_opcAsignarCitaActionPerformed

    private void opcConsultarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcConsultarPacienteActionPerformed
        // TODO add your handling code here:
        // Vamos a llamar la otra ventana
        //Creamos un objeto
        ConsultarPaciente ventanaConsultarPaciente = new ConsultarPaciente();
        escritorio.add(ventanaConsultarPaciente);
        ventanaConsultarPaciente.show();
    }//GEN-LAST:event_opcConsultarPacienteActionPerformed

    private void opcConsultarMédicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcConsultarMédicoActionPerformed
        // TODO add your handling code here:
        // Vamos a llamar la otra ventana
        //Creamos un objeto
        ConsultarMedico ventanaConsultarMedico = new ConsultarMedico();
        escritorio.add(ventanaConsultarMedico);
        ventanaConsultarMedico.show();
    }//GEN-LAST:event_opcConsultarMédicoActionPerformed

    private void opcConsultarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcConsultarCitaActionPerformed
        // TODO add your handling code here:
        // Vamos a llamar la otra ventana
        //Creamos un objeto
        ConsultarCita ventanaConsultarCita = new ConsultarCita();
        escritorio.add(ventanaConsultarCita);
        ventanaConsultarCita.show();
    }//GEN-LAST:event_opcConsultarCitaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProyectoCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProyectoCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProyectoCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProyectoCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProyectoCitas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuItem opcAsignarCita;
    private javax.swing.JMenuItem opcConsultarCita;
    private javax.swing.JMenuItem opcConsultarMédico;
    private javax.swing.JMenuItem opcConsultarPaciente;
    private javax.swing.JMenuItem opcRegistrarMedico;
    private javax.swing.JMenuItem opcRegistrarPaciente;
    // End of variables declaration//GEN-END:variables
}
